### PR TITLE
Updated release history for version 0.2.1

### PR DESCRIPTION
**Pull request by janjakubnanista**

### CODE REVIEW

**Comment by ryanseddon** [comment]
:+1:

**Comment by ryanseddon** [comment]
btw @janjakubnanista you know you have contributor rights? Feel free to push readme updates or version bumps straight to master.

**Comment by janjakubnanista** [comment]
@ryanseddon I didn't know that... I was trying to publish new version via `npm publish` but that didn't work.

**Comment by ryanseddon** [comment]
Yep npm publish is under my account, it doesn't take into account
contributors on github.

**Pull request merged**
